baseURL = 'https://asukaonly.github.io'
languageCode = 'en-us'
title = '404 NOT FOUND'
theme = "hugo-coder"


enableEmoji = true
buildFuture = true
# 样式参考 https://swapoff.org/chroma/playground
[markup.highlight]
style = 'manni'
