env = "production"

author = "luyanliang"

keywords = ["blog", "developer", "personal"]
images = ["/avatar.png"]
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = true

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = false
disableSpecial1stPost = false
disableScrollToTop = false
hidemeta = false
hideSummary = false

tocopen = true
UseHugoToc = true
showtoc = true

comments = true


[assets]
favicon = "avatar.png"
favicon16x16 = "avatar.png"
favicon32x32 = "avatar.png"
apple_touch_icon = "avatar.png"
safari_pinned_tab = "avatar.png"


[profileMode]
enabled = true
url = "https://github.com/"
imageUrl = "avatar.png"
info = ["What is mind? ", "No matter. ", "What is matter? ", "Never mind."]
imageHeight = 250
imageWidth = 250

[[profileMode.buttons]]
name = "blog"
url = "/posts"

[[socialIcons]]
name = "github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/asukaonly"
target = "_blank"
[[socialIcons]]
name = "x"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://twitter.com/my_lifefor_aiur"
target = "_blank"

[analytics.google]
SiteVerificationTag = "XYZabc"

[cover]
hidden = true
