baseURL = 'https://asukaonly.github.io'
languageCode = 'zh-cn'
title = '404 NOT FOUND'
theme = "PaperMod"

hasCJKLanguage = true

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[markup.goldmark.renderer]
unsafe = true
